package main

import (
	"fmt"

	"github.com/kishan-thanki/stats"
)

func main() {
	fmt.Println("==================================================")
	fmt.Println("    STATS: EXHAUSTIVE GENERIC DEMONSTRATION    ")
	fmt.Println("==================================================")

	fmt.Println("\n--- Average ---")
	res_Average_int, _ := stats.Average([]int{1, 2, 3})
	fmt.Printf("int:       %v\n", res_Average_int)
	res_Average_int8, _ := stats.Average([]int8{1, 2, 3})
	fmt.Printf("int8:      %v\n", res_Average_int8)
	res_Average_int16, _ := stats.Average([]int16{1, 2, 3})
	fmt.Printf("int16:     %v\n", res_Average_int16)
	res_Average_int32, _ := stats.Average([]int32{1, 2, 3})
	fmt.Printf("int32:     %v\n", res_Average_int32)
	res_Average_int64, _ := stats.Average([]int64{1, 2, 3})
	fmt.Printf("int64:     %v\n", res_Average_int64)
	res_Average_uint, _ := stats.Average([]uint{1, 2, 3})
	fmt.Printf("uint:      %v\n", res_Average_uint)
	res_Average_uint8, _ := stats.Average([]uint8{1, 2, 3})
	fmt.Printf("uint8:     %v\n", res_Average_uint8)
	res_Average_uint16, _ := stats.Average([]uint16{1, 2, 3})
	fmt.Printf("uint16:    %v\n", res_Average_uint16)
	res_Average_uint32, _ := stats.Average([]uint32{1, 2, 3})
	fmt.Printf("uint32:    %v\n", res_Average_uint32)
	res_Average_uint64, _ := stats.Average([]uint64{1, 2, 3})
	fmt.Printf("uint64:    %v\n", res_Average_uint64)
	res_Average_uintptr, _ := stats.Average([]uintptr{1, 2, 3})
	fmt.Printf("uintptr:   %v\n", res_Average_uintptr)
	res_Average_float32, _ := stats.Average([]float32{1.5, 2.5, 3.5})
	fmt.Printf("float32:   %v\n", res_Average_float32)
	res_Average_float64, _ := stats.Average([]float64{1.5, 2.5, 3.5})
	fmt.Printf("float64:   %v\n", res_Average_float64)

	fmt.Println("\n--- Median ---")
	res_Median_int, _ := stats.Median([]int{1, 2, 3})
	fmt.Printf("int:       %v\n", res_Median_int)
	res_Median_int8, _ := stats.Median([]int8{1, 2, 3})
	fmt.Printf("int8:      %v\n", res_Median_int8)
	res_Median_int16, _ := stats.Median([]int16{1, 2, 3})
	fmt.Printf("int16:     %v\n", res_Median_int16)
	res_Median_int32, _ := stats.Median([]int32{1, 2, 3})
	fmt.Printf("int32:     %v\n", res_Median_int32)
	res_Median_int64, _ := stats.Median([]int64{1, 2, 3})
	fmt.Printf("int64:     %v\n", res_Median_int64)
	res_Median_uint, _ := stats.Median([]uint{1, 2, 3})
	fmt.Printf("uint:      %v\n", res_Median_uint)
	res_Median_uint8, _ := stats.Median([]uint8{1, 2, 3})
	fmt.Printf("uint8:     %v\n", res_Median_uint8)
	res_Median_uint16, _ := stats.Median([]uint16{1, 2, 3})
	fmt.Printf("uint16:    %v\n", res_Median_uint16)
	res_Median_uint32, _ := stats.Median([]uint32{1, 2, 3})
	fmt.Printf("uint32:    %v\n", res_Median_uint32)
	res_Median_uint64, _ := stats.Median([]uint64{1, 2, 3})
	fmt.Printf("uint64:    %v\n", res_Median_uint64)
	res_Median_uintptr, _ := stats.Median([]uintptr{1, 2, 3})
	fmt.Printf("uintptr:   %v\n", res_Median_uintptr)
	res_Median_float32, _ := stats.Median([]float32{1.5, 2.5, 3.5})
	fmt.Printf("float32:   %v\n", res_Median_float32)
	res_Median_float64, _ := stats.Median([]float64{1.5, 2.5, 3.5})
	fmt.Printf("float64:   %v\n", res_Median_float64)

	fmt.Println("\n--- Mode ---")
	res_Mode_int, _ := stats.Mode([]int{1, 2, 3})
	fmt.Printf("int:       %v\n", res_Mode_int)
	res_Mode_int8, _ := stats.Mode([]int8{1, 2, 3})
	fmt.Printf("int8:      %v\n", res_Mode_int8)
	res_Mode_int16, _ := stats.Mode([]int16{1, 2, 3})
	fmt.Printf("int16:     %v\n", res_Mode_int16)
	res_Mode_int32, _ := stats.Mode([]int32{1, 2, 3})
	fmt.Printf("int32:     %v\n", res_Mode_int32)
	res_Mode_int64, _ := stats.Mode([]int64{1, 2, 3})
	fmt.Printf("int64:     %v\n", res_Mode_int64)
	res_Mode_uint, _ := stats.Mode([]uint{1, 2, 3})
	fmt.Printf("uint:      %v\n", res_Mode_uint)
	res_Mode_uint8, _ := stats.Mode([]uint8{1, 2, 3})
	fmt.Printf("uint8:     %v\n", res_Mode_uint8)
	res_Mode_uint16, _ := stats.Mode([]uint16{1, 2, 3})
	fmt.Printf("uint16:    %v\n", res_Mode_uint16)
	res_Mode_uint32, _ := stats.Mode([]uint32{1, 2, 3})
	fmt.Printf("uint32:    %v\n", res_Mode_uint32)
	res_Mode_uint64, _ := stats.Mode([]uint64{1, 2, 3})
	fmt.Printf("uint64:    %v\n", res_Mode_uint64)
	res_Mode_uintptr, _ := stats.Mode([]uintptr{1, 2, 3})
	fmt.Printf("uintptr:   %v\n", res_Mode_uintptr)
	res_Mode_float32, _ := stats.Mode([]float32{1.5, 2.5, 3.5})
	fmt.Printf("float32:   %v\n", res_Mode_float32)
	res_Mode_float64, _ := stats.Mode([]float64{1.5, 2.5, 3.5})
	fmt.Printf("float64:   %v\n", res_Mode_float64)
	res_Mode_string, _ := stats.Mode([]string{"apple", "banana", "apple"})
	fmt.Printf("string:    %v\n", res_Mode_string)

	fmt.Println("\n--- SumSlice ---")
	res_SumSlice_int, _ := stats.SumSlice([]int{1, 2, 3})
	fmt.Printf("int:       %v\n", res_SumSlice_int)
	res_SumSlice_int8, _ := stats.SumSlice([]int8{1, 2, 3})
	fmt.Printf("int8:      %v\n", res_SumSlice_int8)
	res_SumSlice_int16, _ := stats.SumSlice([]int16{1, 2, 3})
	fmt.Printf("int16:     %v\n", res_SumSlice_int16)
	res_SumSlice_int32, _ := stats.SumSlice([]int32{1, 2, 3})
	fmt.Printf("int32:     %v\n", res_SumSlice_int32)
	res_SumSlice_int64, _ := stats.SumSlice([]int64{1, 2, 3})
	fmt.Printf("int64:     %v\n", res_SumSlice_int64)
	res_SumSlice_uint, _ := stats.SumSlice([]uint{1, 2, 3})
	fmt.Printf("uint:      %v\n", res_SumSlice_uint)
	res_SumSlice_uint8, _ := stats.SumSlice([]uint8{1, 2, 3})
	fmt.Printf("uint8:     %v\n", res_SumSlice_uint8)
	res_SumSlice_uint16, _ := stats.SumSlice([]uint16{1, 2, 3})
	fmt.Printf("uint16:    %v\n", res_SumSlice_uint16)
	res_SumSlice_uint32, _ := stats.SumSlice([]uint32{1, 2, 3})
	fmt.Printf("uint32:    %v\n", res_SumSlice_uint32)
	res_SumSlice_uint64, _ := stats.SumSlice([]uint64{1, 2, 3})
	fmt.Printf("uint64:    %v\n", res_SumSlice_uint64)
	res_SumSlice_uintptr, _ := stats.SumSlice([]uintptr{1, 2, 3})
	fmt.Printf("uintptr:   %v\n", res_SumSlice_uintptr)
	res_SumSlice_float32, _ := stats.SumSlice([]float32{1.5, 2.5, 3.5})
	fmt.Printf("float32:   %v\n", res_SumSlice_float32)
	res_SumSlice_float64, _ := stats.SumSlice([]float64{1.5, 2.5, 3.5})
	fmt.Printf("float64:   %v\n", res_SumSlice_float64)

	fmt.Println("\n--- MinSlice ---")
	res_MinSlice_int, _ := stats.MinSlice([]int{1, 2, 3})
	fmt.Printf("int:       %v\n", res_MinSlice_int)
	res_MinSlice_int8, _ := stats.MinSlice([]int8{1, 2, 3})
	fmt.Printf("int8:      %v\n", res_MinSlice_int8)
	res_MinSlice_int16, _ := stats.MinSlice([]int16{1, 2, 3})
	fmt.Printf("int16:     %v\n", res_MinSlice_int16)
	res_MinSlice_int32, _ := stats.MinSlice([]int32{1, 2, 3})
	fmt.Printf("int32:     %v\n", res_MinSlice_int32)
	res_MinSlice_int64, _ := stats.MinSlice([]int64{1, 2, 3})
	fmt.Printf("int64:     %v\n", res_MinSlice_int64)
	res_MinSlice_uint, _ := stats.MinSlice([]uint{1, 2, 3})
	fmt.Printf("uint:      %v\n", res_MinSlice_uint)
	res_MinSlice_uint8, _ := stats.MinSlice([]uint8{1, 2, 3})
	fmt.Printf("uint8:     %v\n", res_MinSlice_uint8)
	res_MinSlice_uint16, _ := stats.MinSlice([]uint16{1, 2, 3})
	fmt.Printf("uint16:    %v\n", res_MinSlice_uint16)
	res_MinSlice_uint32, _ := stats.MinSlice([]uint32{1, 2, 3})
	fmt.Printf("uint32:    %v\n", res_MinSlice_uint32)
	res_MinSlice_uint64, _ := stats.MinSlice([]uint64{1, 2, 3})
	fmt.Printf("uint64:    %v\n", res_MinSlice_uint64)
	res_MinSlice_uintptr, _ := stats.MinSlice([]uintptr{1, 2, 3})
	fmt.Printf("uintptr:   %v\n", res_MinSlice_uintptr)
	res_MinSlice_float32, _ := stats.MinSlice([]float32{1.5, 2.5, 3.5})
	fmt.Printf("float32:   %v\n", res_MinSlice_float32)
	res_MinSlice_float64, _ := stats.MinSlice([]float64{1.5, 2.5, 3.5})
	fmt.Printf("float64:   %v\n", res_MinSlice_float64)

	fmt.Println("\n--- MaxSlice ---")
	res_MaxSlice_int, _ := stats.MaxSlice([]int{1, 2, 3})
	fmt.Printf("int:       %v\n", res_MaxSlice_int)
	res_MaxSlice_int8, _ := stats.MaxSlice([]int8{1, 2, 3})
	fmt.Printf("int8:      %v\n", res_MaxSlice_int8)
	res_MaxSlice_int16, _ := stats.MaxSlice([]int16{1, 2, 3})
	fmt.Printf("int16:     %v\n", res_MaxSlice_int16)
	res_MaxSlice_int32, _ := stats.MaxSlice([]int32{1, 2, 3})
	fmt.Printf("int32:     %v\n", res_MaxSlice_int32)
	res_MaxSlice_int64, _ := stats.MaxSlice([]int64{1, 2, 3})
	fmt.Printf("int64:     %v\n", res_MaxSlice_int64)
	res_MaxSlice_uint, _ := stats.MaxSlice([]uint{1, 2, 3})
	fmt.Printf("uint:      %v\n", res_MaxSlice_uint)
	res_MaxSlice_uint8, _ := stats.MaxSlice([]uint8{1, 2, 3})
	fmt.Printf("uint8:     %v\n", res_MaxSlice_uint8)
	res_MaxSlice_uint16, _ := stats.MaxSlice([]uint16{1, 2, 3})
	fmt.Printf("uint16:    %v\n", res_MaxSlice_uint16)
	res_MaxSlice_uint32, _ := stats.MaxSlice([]uint32{1, 2, 3})
	fmt.Printf("uint32:    %v\n", res_MaxSlice_uint32)
	res_MaxSlice_uint64, _ := stats.MaxSlice([]uint64{1, 2, 3})
	fmt.Printf("uint64:    %v\n", res_MaxSlice_uint64)
	res_MaxSlice_uintptr, _ := stats.MaxSlice([]uintptr{1, 2, 3})
	fmt.Printf("uintptr:   %v\n", res_MaxSlice_uintptr)
	res_MaxSlice_float32, _ := stats.MaxSlice([]float32{1.5, 2.5, 3.5})
	fmt.Printf("float32:   %v\n", res_MaxSlice_float32)
	res_MaxSlice_float64, _ := stats.MaxSlice([]float64{1.5, 2.5, 3.5})
	fmt.Printf("float64:   %v\n", res_MaxSlice_float64)
}
